[review]
allow-users = [
  "nolouch",
  "HunDunDM",
  "rleungx",
  "disksing",
  "JmPotato",
  "lhy1024",
  "AndreMouche",
  "bufferflies",
  "CabinfeverB",
  "Yisaer",
  "HuSharp",
  "Connor1996",
  "matchge-ca",
  "innerr",
  "hnes",
  "binshi-bing",
]
block-comments = [
  "/run-",
  "/merge",
  "/rebuild",
  "/ok-to-test",
  "/test build",
]
block-labels = [
  "cherry-pick-approved",
  "status/can-merge",
]
block-users = [
  "sre-bot",
  "ti-chi-bot",
  "ti-srebot",
  "codecov",
  "codecov[bot]",
  "codecov-commenter",
  "CLAassistant",
  "hound[bot]",
]
lgtm-comments = [
  "/lgtm",
  "LGTM",
]

# Could also be set with the environment variable:
#   - GHSTATS_GITHUB_TOKEN
#   - GHSTATS_FEISHU_WEBHOOK_TOKEN
[review.access]
feishu-webhook-token = ""
github-token = ""

[[review.repos]]
name = "PD"
pr-query = [
  """
repo:tikv/pd
""",
  """
repo:tikv/client-go
""",
  """
repo:tikv/tikv
""",
  """
repo:pingcap/tidb
""",
  """
repo:pingcap/kvproto
""",
  """
repo:pingcap/docs
""",
  """
repo:pingcap/docs-cn
""",
]
