name: Weekly Github Review Stats of Scheduling Team

on:
  schedule:
    # UTC+8 14:00 on Friday.
    - cron: "0 6 * * 5"
  workflow_dispatch:

jobs:
  review-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.0'
      - run: |
          make run-weekly-review
        env:
          GHSTATS_GITHUB_TOKEN: ${{ secrets.GHSTATS_GITHUB_TOKEN }}
          GHSTATS_FEISHU_WEBHOOK_TOKEN: ${{ secrets.GHSTATS_FEISHU_WEBHOOK_TOKEN }}
